#apiVersion: v1
#kind: Namespace
#metadata:
#  name: ncm-issuer
#---
apiVersion: certmanager.ncm.nokia.com/v1
kind: Issuer
metadata:
   name: ncm
   namespace: ncm-issuer
spec:
   caName: SubCA
   # caID: HREF_FROM_NCM
   provisioner:
      mainAPI: NCM_SRV
      httpClientTimeout: 15s
      healthCheckerInterval: 3m
      authRef:
         name: ncm-issuer
         namespace: ncm-issuer
      tlsRef:
         name: ncm-issuer-bundle
         namespace: ncm-issuer
   # profileId: PROFILE_ID
   reenrollmentOnRenew: false
   useProfileIDForRenew: false
   noRoot: false
   chainInSigner: false
   onlyEECert: false
