---
apiVersion: v1
kind: Service
metadata:
  name: {{include "ncm-issuer.name" .}}-svc
  labels:
    {{- if .Values.prometheus.serviceMonitor.enabled }}
    release: {{ .Values.prometheus.serviceMonitor.selectorLabel }}
    {{- end }}
    {{- include "ncm-issuer.labels.standard" . | nindent 4}}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      protocol: TCP
      name: {{ .Values.service.name }}-http
      targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "ncm-issuer.template.labels" . | nindent 4 }}
