{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.binding }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ncm-issuer.labels.standard" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.sa }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.role }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}